version: "3"
services:
  satisfactory-server:
    container_name: "satisfactory-server"
    hostname: "satisfactory-server"
    image: "wolveix/satisfactory-server:latest"
    ports:
      - "7777:7777/udp"
      - "15000:15000/udp"
      - "15777:15777/udp"
    volumes:
      - "/home/ec2-user/satisfactory-config:/config"
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=true
      - AUTOPAUSE=true
      - AUTOSAVEONDISCONNECT=true
      - AUTOSAVENUM=5
      - AUTOSAVEINTERVAL=1800
    restart: unless-stopped
